# Generated by Django 2.1.5 on 2019-02-11 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_contents_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='title',
        ),
        migrations.AddField(
            model_name='contents',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
