# Generated by Django 2.1.5 on 2019-02-15 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20190211_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
