# Generated by Django 2.1.5 on 2019-03-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20190308_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='message',
            field=models.TextField(default='no message'),
            preserve_default=False,
        ),
    ]
