# Generated by Django 2.1.5 on 2019-04-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_auto_20190410_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='anchor_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anchor_child', to='contents.Response'),
        ),
        migrations.AddField(
            model_name='response',
            name='is_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='response',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
