# Generated by Django 2.1.5 on 2019-04-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_auto_20190414_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='anchor_parent',
        ),
        migrations.AddField(
            model_name='response',
            name='anchor_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anchor_child', to='contents.Response'),
        ),
    ]
