# Generated by Django 2.1.5 on 2019-04-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_auto_20190414_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='anchor_parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='anchor_child', to='contents.Response'),
        ),
    ]
