# Generated by Django 2.1.5 on 2019-04-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_remove_response_anchor_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='anchor_parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='anchor_child', to='contents.Response'),
        ),
    ]
