# Generated by Django 2.1.5 on 2019-04-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_auto_20190417_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_number',
            field=models.IntegerField(default=0),
        ),
    ]
